#!/usr/bin/env python

import sys, os, re, subprocess

# Clear all ip netns is "ip netns list"

toClear = subprocess.check_output("ip netns list", shell=True)

for i in  filter(lambda x: not re.match(r'^\s*$', x), toClear) :
    subprocess.call("ip netns delete {}".format(i), shell=True)
