#!/usr/bin/env python

import sys, os
from node import *
from net import *

# ./build topos/file.py toponame [outdir]
# custom exec inspired by mininet

def usage():
	print 'Usage: %s topofile.py toponame [outdir]' % (sys.argv[0])
	sys.exit(-1)

if len(sys.argv) < 3 or len(sys.argv) > 4:
	usage()

outdir='.'
if len(sys.argv) == 4:
	outdir = sys.argv[3]

topos = {}

sys.path.append('.')

customs = {}
execfile(sys.argv[1], customs, customs)
for name, val in customs.iteritems():
	if name == 'topos':
		globals()['topos'].update(val)
	else:
		globals()[name] = val

topo = topos[sys.argv[2]]()

os.chdir(outdir)

net = Nanonet(topo)
net.start()

f = open(sys.argv[2]+'.topo.sh', 'w')

for n in net.topo.nodes:
	f.write('# %s loop: %s\n' % (n.name, n.addr))
f.write('\n')

net.dump_commands(lambda x: f.write('%s\n' % x))
f.close()
